server:
  port: 8002
#端口 随意取

mybatis:
  config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
#并不打算，写一堆的xml文件   所以，使用动态查询
#  mapper-locations:
#    - "classpath:mybatis/mapper/**/*.xml"                     # mapper映射文件
#  type-aliases-package: com.lzj.springcloud.entity            # 别名类所在包

spring:
  application:
    name: springcloudProvider                          #微服务的名字
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC    # 数据库名称
    username: root
    password:
    dbcp2:
      initial-size: 5                                         # 初始化连接数
      max-total: 5                                            # 最大连接数
      max-wait-millis: 200                                    # 等待连接获取的最大超时时间
      min-idle: 5                                             # 数据库连接池的最小维持连接数
